---
language: python
python: "2.7"
os: linux
dist: xenial
env:
  - OS_TYPE=centos OS_VERSION=7

branches:
  only:
  - master
#  - stable

sudo: required

services:
  - docker

addons:
  apt:
    sources:
      - ppa:ansible/ansible
    packages:
      - ansible

before_install:
  #- sudo apt-get -qy update
  #- sudo apt-get -qy -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" dist-upgrade
  - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
  - sudo service docker restart
  - sleep 5
  # Get docker
  - sudo docker pull williamyeh/ansible:${OS_TYPE}${OS_VERSION}-onbuild

install:
  # Check ansible version
  - ansible --version
  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  #- ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Test Demo case 1
  #- ansible-playbook tests/test.yml -i tests/inventory
  # test login pages
  #- curl -i -s --insecure --data "user=ncadmin&password=" https://localhost/index.php/login | egrep -q "Location:.*/apps/files/"

 # Run tests in Container
 - sudo docker run -i --rm -v "${TRAVIS_BUILD_DIR}:/mnt/" williamyeh/ansible:${OS_TYPE}${OS_VERSION}-onbuild bash -c "/mnt/tests/docker-run.sh /mnt/tests" > /tmp/result-${OS_TYPE}${OS_VERSION}.log
 - echo "==> Validating the test results..."
 - sh -c "[ -s /tmp/result-${OS_TYPE}${OS_VERSION}.log ]"

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
